# development:
#   server: "http://localhost:9292/faye"
#   secret_token: "secret"
# test:
#   server: "http://localhost:9292/faye"
#   secret_token: "secret"
# production:
#   server: "http://example.com/faye"
#   secret_token: "2b236c2fba47f8b2e7a6df29c0246da616d8c92d304a3756b744315f03ea8350"
#   signature_expiration: 3600 # one hour


development:
  #server: "http://localhost:9292/faye"
  server: "http://192.168.9.247:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://ramifayeserver.herokuapp.com/faye"
  secret_token: "e0317cbedf3ee4930adefd0c64f1ec9638dc05233d7234ce531997da652a4349"
  signature_expiration: 86400 # one day
